### ISSUE TITLE
A warning!

### ISSUE THREAD

**Issue by WeTogetherDo** [LarsGit223/dokuwiki-plugin-randominc#4]
I installed plugin randominc and I writed the following code in wiki:

{{randominc>ns1:ns2}}

And I found nothing happend but a warning:

Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in C:\DokuWikiStick\dokuwiki\lib\plugins\randominc\syntax.php on line 62

**Comment by lpaulsen93** [comment]
I could only re-produce that problem if I specify a non-existing namespace. That means the problem occurs if no pages are found in the specified namespace. Reasons could be:
- the namespace does not exist
- there are pages but the user has got no read permission

In such a situation the plugin will now output this message _"randominc: no page found."_ instead of causing a warning. Please re-install and test.

If you then get the message you need to check the namespace and your permissions.

**Comment by lpaulsen93** [comment]
@WeTogetherDo: any news? Did you have a chance to test it?

**Comment by lpaulsen93** [comment]
The fix is now included in the new release. So I close this now.
